plugins {
    id 'java'
    id 'application'
}

group = 'daa'
version = '1.0.0'
description = 'DAA Assignment 1 - Divide and Conquer & Asymptotic Notations'


repositories {
    mavenCentral()
    flatDir {
        dirs 'lib'
    }
}

dependencies {
    testImplementation fileTree(dir: 'lib', include: ['*.jar'])
}

application {
    mainClass = 'daa.Main'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.register('daa.Main.main()', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'daa.Main'
}

tasks.register('daa.AllTestsRunner.main()', JavaExec) {
    classpath = sourceSets.test.runtimeClasspath
    mainClass = 'daa.AllTestsRunner'
}

tasks.register('Main.main()', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'daa.Main'
}

tasks.register('AllTestsRunner.main()', JavaExec) {
    classpath = sourceSets.test.runtimeClasspath
    mainClass = 'daa.AllTestsRunner'
}

tasks.register('runAllTests', JavaExec) {
    classpath = sourceSets.test.runtimeClasspath
    mainClass = 'daa.AllTestsRunner'
}
