plugins {
    id 'java'
    id 'application'
}

group = 'com.daa'
version = '1.0.0'
description = 'DAA Assignment 1 - Divide and Conquer & Asymptotic Notations'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    flatDir {
        dirs 'lib'
    }
}

dependencies {
    testImplementation fileTree(dir: 'lib', include: ['*.jar'])
}

application {
    mainClass = 'com.daa.benchmark.BenchmarkRunner'
}

tasks.named('test') {
    useJUnitPlatform()
}
