plugins {
    id 'java'
    id 'application'
}

group = 'daa'
version = '1.0.0'
description = 'DAA Assignment 1 - Divide and Conquer & Asymptotic Notations'


repositories {
    mavenCentral()
    flatDir {
        dirs 'lib'
    }
}

dependencies {
    testImplementation fileTree(dir: 'lib', include: ['*.jar'])
}

application {
    mainClass = 'daa.Main'
}

tasks.named('test') {
    useJUnitPlatform()
}
